### PR TITLE
Fixes UI on vertically longer properties like Vectors

### PR DESCRIPTION
**Pull request by FREEZX**
On vertically longer properties like vectors, there was a layout issue because each property column was rendered separately. With this change, the entirety of a single property is rendered as a single row (Using EditorGUILayout.BeginHorizontal), and all rows are rendered in a single column (EditorGUILayout.BeginVertical), eliminating the issue.

### CODE REVIEW

**Comment by lgarczyn** [comment]
Hello, thanks for the contribution!

The reason there was a need for splitting the table into columns first was to ensure alignment between rows. How does your version deal with this?

**Comment by FREEZX** [comment]
It's still split into the same columns and the desired width for the column is set using `EditorGUILayout.VerticalScope scope = new(GUILayout.Width(width));`. Here's how it looks like now with a few different kinds of fields:
523-471-max

**Comment by lgarczyn** [comment]
I've fixed this issue using MultiFieldProperty instead in the latest commit

**Comment by FREEZX** [comment]
Awesome, that fixes it, thanks!

**Pull request closed without merging**
